### PR TITLE
Rewrite requestArrivalData

### PR DESCRIPTION
**Pull request by nifty**
Rewrites most of the functionality around `requestArrivalData`. We now only use built in packages, so we don't need to rely on any third party libraries.

I've also ensured it adheres to the Golint rules. The tools is written by the Golang people, so I guess we should try to adhere to it as much as possible? Still quite a few places which throws errors.

~~This includes the changes in #1, so it would be wise to merge that first.~~

### CODE REVIEW

**Comment by nifty** [comment]
I've updated the branch and removed the commit specific to #1.

**Comment by michaelenger** [comment]
I met Chris earlier today and he told me magical things about autoformatting which is included in go. The `go fmt` command will format your code to fit the standard. I think I might be in love.

**Comment by nifty** [comment]
Yes. I had it auto format automatically in Atom with the Go-plus package, but I turned it off because it removes imports until they are actually used, which got kind of annoying. But I believe it should also auto add imports based on the functions you use, so I guess maybe it's quite nice if it works.

**Comment by michaelenger** [comment]
I'm not sure about exposing the types and functions in **ruter.go**. I don't see a reason why people using the sanntid package would need to call the Ruter API functions directly. If we are going to be changing this to be a more generic Ruter API package, then we should restructure it accordingly.

_I am assuming that by capitalizing the first letter we are exposing them as a public API.. Go is weird._

**Comment by nifty** [comment]
Yep. Makes sense. I'll update the code.

**Pull request merged**
